import { useEffect } from "react";
import { Link } from "react-router-dom";

const PrivacyPolicy = () => {
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth"});
  }, []);
  
  return (
    <div className="px-3 md:px-10 lg:px-20 py-10 md:py-20">
      <h2 className="text-2xl md:text-4xl font-bold">
        Privacy Policy for Makayiram Retreat
      </h2>
      <p className="my-6 tetx-xs md:font-lg">Last updated: April 08, 2024</p>
      <p className="text-2xl font-normal">
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p className="text-2xl py-6 font-normal">
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>
      <h2 className="text md:text-4xl font-bold">
        Interpretation and Definitions
      </h2>
      <h3 className="text-3xl font-bold my-6">Interpretation</h3>
      <p className="text-2xl
       py-4">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>
      <h3 className="text-3xl font-bold py-5">Definitions</h3>
      <p className="text-2xl
       font-semibold">
        For the purposes of this Privacy Policy:
      </p>
      <ul className="list-disc mx-10 my-6 space-y-5 text-2xl
      ">
        <li>
          <span className="font-bold">Account </span>
          means a unique account created for You to access our Service or parts
          of our Service.
        </li>
        <li>
          <span className="font-bold mr-2">Affiliate </span>
           means an entity that controls, is controlled by or is under common
          control with a party, where "control" means ownership of 50% or more
          of the shares, equity interest or other securities entitled to vote
          for election of directors or other managing authority.
        </li>
        <li>
          <span className="font-bold">Company </span>
          Company (referred to as either "the Company", "We", "Us" or "Our" in
          this Agreement) refers to Makayiram Plantations Pvt Ltd, Pothamedu,
          Munnar 685612 Kerala.
        </li>
        <li>
          <span className="font-bold">Cookies </span>
          are 2xl
          all files that are placed on Your computer, mobile device or any
          other device by a website, containing the details of Your browsing
          history on that website among its many uses.
        </li>
        <li>
          <span className="font-bold mr-2">Country</span>
           refers to: Kerala, India
        </li>
        <li>
          <span className="font-bold mr-2">Device </span>
          means any device that can access the Service such as a computer, a
          cellphone or a digital tablet.
        </li>
        <li>
          <span className="font-bold mr-2">Personal Data </span>
          is any information that relates to an identified or identifiable
          individual.
        </li>
        <li>
          <span className="font-bold mr-2">Service </span>
          refers to the Website.
        </li>
        <li>
          <span className="font-bold mr-2">Service Provider </span>
          means any natural or legal person who processes the data on behalf of
          the Company. It refers to third-party companies or individuals
          employed by the Company to facilitate the Service, to provide the
          Service on behalf of the Company, to perform services related to the
          Service or to assist the Company in analyzing how the Service is used.
        </li>
        <li>
          <span className="font-bold mr-2">Usage Data </span>
          refers to data collected automatically, either generated by the use of
          the Service or from the Service infrastructure itself (for example,
          the duration of a page visit).
        </li>
        <li>
          <span className="font-bold mr-2">Website </span>
          refers to Makayiram Retreat, accessible from
          <Link
            to="https://makayiram.com/"
            className="text-green-500 underline ml-2"
          >
             www.makayiram.com
          </Link>
        </li>
        <li>
          <span className="font-bold mr-2">You </span>
          means the individual accessing or using the Service, or the company,
          or other legal entity on behalf of which such individual is accessing
          or using the Service, as applicable.
        </li>
      </ul>
      <h1 className="text-3xl font-bold my-12">
        Collecting and Using Your Personal Data
      </h1>
      <h2 className="text-2xl font-bold">Types of Data Collected</h2>
      <h3 className="text-2xl py-6 font-semibold">Personal Data</h3>
      <p className="text-2xl
      ">
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul className="list-disc mx-10 my-6 space-y-5 text-2xl
      ">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
      </ul>
      <h3 className="text-2xl py-6 font-semibold">Usage Data</h3>
      <p className="text-2xl
       my-4">
        Usage Data is collected automatically when using the Service.
      </p>
      <p className="text-2xl
       my-4">
        Usage Data may include information such as Your Device's Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>
      <p className="text-2xl
       my-4">
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.
      </p>
      <p className="text-2xl
       my-6">
        We may also collect information that Your browser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        device.
      </p>
      <h2 className="text-2xl font-bold my-4">Use of Your Personal Data</h2>
      <p className="text-2xl
      ">
        The Company may use Personal Data for the following purposes:
      </p>
      <ul className="list-disc mx-10 my-6 space-y-5 text-2xl
      ">
        <li>
          <span className="font-bold">To provide and maintain our Service</span>
          , including to monitor the usage of our Service.
        </li>
        <li>
          <span className="font-bold mr-2">To manage Your Account: </span>
          to manage Your registration as a user of the Service. The Personal
          Data You provide can give You access to different functionalities of
          the Service that are available to You as a registered user.
        </li>
        <li>
          <span className="font-bold">For the performance of a contract: </span>
          the development, compliance and undertaking of the purchase contract
          for the products, items or services You have purchased or of any other
          contract with Us through the Service.
        </li>
        <li>
          <span className="font-bold">To contact You: </span>
          To contact You by email, telephone calls,
          SMS, or other equivalent
          forms of electronic communication, such as a mobile application's push
          notifications regarding updates or informative communications related
          to the functionalities, products or contracted services, including the
          security updates, when necessary or reasonable for their
          implementation.
        </li>
        <li>
          <span className="font-bold mr-2">To provide You </span>
          with news, special offers and general information about other goods,
          services and events which we offer that are similar to those that you
          have already purchased or enquired about unless You have opted not to
          receive such information.
        </li>
        <li>
          <span className="font-bold mr-2">To manage Your requests: </span>
          To attend and manage Your requests to Us.
        </li>
        <li>
          <span className="font-bold mr-2">For business transfers: </span>
          We may use Your information to evaluate or conduct a merger,
          divestiture, restructuring, reorganization, dissolution, or other sale
          or transfer of some or all of Our assets, whether as a going concern
          or as part of bankruptcy, liquidation, or similar proceeding, in which
          Personal Data held by Us about our Service users is among the assets
          transferred.
        </li>
        <li>
          <span className="font-bold mr-2"> For other purposes: </span>
          We may use Your information for other purposes, such as data analysis,
          identifying usage trends, determining the effectiveness of our
          promotional campaigns and to evaluate and improve our Service,
          products, services, marketing and your experience.
        </li>
      </ul>
      <p>We may share Your personal information in the following situations:</p>
      <ul className="list-disc mx-10 my-6 space-y-5 text-2xl
      ">
        <li>
          <span className="font-bold">With Service Providers: </span>
          We may share Your personal information with Service Providers to
          monitor and analyze the use of our Service, to contact You.
        </li>
        <li>
          <span className="font-bold mr-2">For business transfers: </span>
          We may share or transfer Your personal information in connection with,
          or during negotiations of, any merger, sale of Company assets,
          financing, or acquisition of all or a portion of Our business to
          another company.
        </li>
        <li>
          <span className="font-bold">With Affiliates: </span>
          We may share Your information with Our affiliates, in which case we
          will require those affiliates to honor this Privacy Policy. Affiliates
          include Our parent company and any other subsidiaries, joint venture
          partners or other companies that We control or that are under common
          control with Us.
        </li>
        <li>
          <span className="font-bold">With business partners: </span>
          We may share Your information with Our business partners to offer You
          certain products, services or promotions.
        </li>
        <li>
          <span className="font-bold mr-2">With other users: </span>
          when You share personal information or otherwise interact in the
          public areas with other users, such information may be viewed by all
          users and may be publicly distributed outside.
        </li>
        <li>
          <span className="font-bold mr-2">With Your consent: </span>
          We may disclose Your personal information for any other purpose with
          Your consent.
        </li>
      </ul>
      <h2 className="text-3xl font-bold my-4">Children's Privacy</h2>
      <p className="text-2xl
       my-6">
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13. If You are a parent or guardian and You are aware that
        Your child has provided Us with Personal Data, please contact Us. If We
        become aware that We have collected Personal Data from anyone under the
        age of 13 without verification of parental consent, We take steps to
        remove that information from Our servers.
      </p>
      <p className="text-2xl
       my-6">
        If We need to rely on consent as a legal basis for processing Your
        information and Your country requires consent from a parent, We may
        require Your parent's consent before We collect and use that
        information.
      </p>
      <h2 className="text-3xl font-bold my-4">Links to Other Websites</h2>
      <p className="text-2xl
       my-6">
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party's site. We strongly advise You to review the Privacy Policy
        of every site You visit.
      </p>
      <p className="text-2xl
       my-6">
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>
      <h2 className="text-3xl font-bold my-4">
        Changes to this Privacy Policy
      </h2>
      <p className="text-2xl
       my-6">
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p className="text-2xl
       my-6">
        We will let You know via email and/or a prominent notice on Our Service,
        prior to the change becoming effective and update the "Last updated"
        date at the top of this Privacy Policy.
      </p>
      <p className="text-2xl
       my-6">
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>
      <h2 className="text-3xl font-bold my-4">Contact Us</h2>
      <p className="text-2xl
       my-6">
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <a className="text-2xl
      " href="mailto:info@makayiram.com">
        By email: <span className="underline">info@makayiram.com</span>
      </a>
    </div>
  );
};

export default PrivacyPolicy;
